### ISSUE TITLE
examination details : null pointer in rights

### ISSUE THREAD

**Issue by julien-louis** [fli-iam/shanoir-ng#1041]
!!! Non blocking - just adds useless logs !!!

```
java.lang.NullPointerException: null
	at org.shanoir.ng.study.rights.StudyRightsService.hasRightOnStudy(StudyRightsService.java:46)
	at org.shanoir.ng.dataset.security.DatasetSecurityService.hasRightOnStudy(DatasetSecurityService.java:83)
...
	at org.shanoir.ng.examination.service.ExaminationServiceImpl$$EnhancerBySpringCGLIB$$99759672.findById(<generated>)
	at org.shanoir.ng.examination.controler.ExaminationApiController.findExaminationById(ExaminationApiController.java:128)
	at org.shanoir.ng.examination.controler.ExaminationApiController$$FastClassBySpringCGLIB$$d94fae79.invoke(<generated>)
...
	at org.shanoir.ng.examination.controler.ExaminationApiController$$EnhancerBySpringCGLIB$$bda81d36.findExaminationById(<generated>)
```

* examination details work as admin, those logs suggest that it doesn't as user or expert
* it could occurs when the user doesn't actually have the right to see this exam

**Comment by Nunien** [comment]
```
StudyUser founded = repo.findByUserIdAndStudyId(userId, studyId);
		return
				founded.getStudyUserRights() != null
				&& founded.getStudyUserRights().contains(StudyUserRight.valueOf(rightStr))
				&& founded.isConfirmed();
```

when the user has no rights on the study, `founded` can only be null

!!! Check if there are other mistakes like this !!!
