### ISSUE TITLE
Problem while importing dataset - File not found

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1119]
Examination 15147

-> Import failed with no specific message.

Error in the logs (dataset):

2021-12-01 14:08:00.969  INFO 1 --- [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#8-1] .s.n.d.c.DatasetAcquisitionApiController : Start dataset acquisition creation of importJob: /tmp/23 for user 23
2021-12-01 14:08:00.969  INFO 1 --- [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#8-1] o.s.ng.importer.service.ImporterService  : createAllDatasetAcquisition: org.shanoir.ng.importer.service.ImporterService@6d794a8 instances: 1
2021-12-01 14:08:00.972  INFO 1 --- [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#8-1] o.s.n.i.s.d.MrDatasetAcquisitionStrategy : Generating DatasetAcquisition for   : *tseR2d1rr12 - SPINE - Rank:0
2021-12-01 14:08:00.973 ERROR 1 --- [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#8-1] o.s.n.i.s.d.MrDatasetAcquisitionStrategy : Unable to retrieve dicom attributes in file /tmp/23/7937894283434783007/SERIES/1.3.12.2.1107.5.2.43.166066.30000021112616052187200011470/dataset0/1.3.12.2.1107.5.2.43.166066.30000021112616052187200011460.dcm

java.io.FileNotFoundException: /tmp/23/7937894283434783007/SERIES/1.3.12.2.1107.5.2.43.166066.30000021112616052187200011470/dataset0/1.3.12.2.1107.5.2.43.166066.30000021112616052187200011460.dcm (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.dcm4che3.io.DicomInputStream.<init>(DicomInputStream.java:143)
	at org.shanoir.ng.dicom.DicomProcessing.getDicomObjectAttributes(DicomProcessing.java:31)
	at org.shanoir.ng.importer.strategies.datasetacquisition.MrDatasetAcquisitionStrategy.generateDatasetAcquisitionForSerie(MrDatasetAcquisitionStrategy.java:82)

In Import:
  iuid=1.3.12.2.1107.5.2.43.166066.30000021112616052187200011460 - ?
2021-12-01 14:07:41.636  INFO 1 --- [pool-3-thread-5] org.dcm4che3.tool.storescp.StoreSCP      : SHANOIR-PROD<-NEURINFO(464): M-RENAME /tmp/shanoir-dcmrcv/tmp/1.3.12.2.1107.5.2.43.166066.30000021112616052187200011460 to /tmp/shanoir-dcmrcv/1.3.12.2.1107.5.2.43.166066.30000021112616052187200011470/1.3.12.2.1107.5.2.43.166066.30000021112616052187200011460.dcm
  iuid=1.3.12.2.1107.5.2.43.166066.30000021112616052187200011460 - ?
2021-12-01 14:07:41.888  WARN 1 --- [AsyncThread-4] ImagesCreatorAndDicomFileAnalyzerService : Process first DICOM file of serie 1.3.12.2.1107.5.2.43.166066.30000021112616052187200011470 SPINE T2 path /tmp/23/7937894283434783007/1.3.12.2.1107.5.2.43.166066.30000021112616052187200011470/1.3.12.2.1107.5.2.43.166066.30000021112616052187200011460.dcm

(nothing quite interesting ?)

Wiating for the archive.

**Comment by jcomedouteau** [comment]
Tried on qualif: no problem.
Julien will test on production on a test study.

**Comment by Nunien** [comment]
No bug on neurinfo prod in a test study
