### ISSUE TITLE
Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by arthursw** [fli-iam/shanoir-ng#1147]
il y a une erreur lors du téléchargement du dataset 93850 sur shanoir-ofsep et shanoir-ofsep-qualif :

```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/139/93850-3D T1 GADO-T1 3D MPRAGE TRA Pr?-GADO_dcm-20211213111842.download/0330110_20190517_3D T1 GADO_1.3.12.2.1107.5.2.50.175763.30000019051711013981000000068.dcm
    at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
    at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
    at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
    at java.base/java.io.File.toPath(File.java:2292)
    at org.shanoir.ng.download.WADODownloaderService.downloadDicomFilesForURLs(WADODownloaderService.java:144)
    at org.shanoir.ng.dataset.controler.DatasetApiController.downloadDatasetById(DatasetApiController.java:367)
```

le point d'interrogation du Pr?-GADO qui devait être un Pré-GADO.

**Comment by jcomedouteau** [comment]
It seems to be linked to the java's locale (not UTF-8 ?)

https://stackoverflow.com/questions/39185613/java-nio-file-invalidpathexception-malformed-input-or-input-contains-unmappable

Either: 
- Rename the output file to avoid non "classic" chars
- Change locale

**Comment by jcomedouteau** [comment]
Works for:
dataset name
examination comment
subject name

Also provokes a bug during the import.
Locale does not seems to work
- Make an SQL script to correct all existing
- Forbib such characters ? (or just transform them ?)

To be discussed with anthony.

**Comment by jcomedouteau** [comment]
select * from dataset_metadata where name like '%é%' COLLATE utf8mb4_bin;

List all forbidden chars ?
