### ISSUE TITLE
OFSEP issue: subject creation (badly named legacy subjects)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1171]
shanoir-ofsep.irisa.fr

Using ShanoirUploader an error occurs, when importing data of center with id "110".
The below issue occurs, because of some "badly named" existing legacy data… a subject name,
that is not conform to the only-number rule, that is normally used. When sh-ng tries to get the
„highest/latest" subject for a center, in our case with the centerId „110“ and just wants to up-count the
subject name, an error is thrown as the subject with the name „11021CRAL" exists in the db and
21CRAL can not be counted up.

java.lang.NumberFormatException: For input string: "21CRAL"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.shanoir.ng.subject.service.SubjectServiceImpl.createAutoIncrement(SubjectServiceImpl.java:166)
	at org.shanoir.ng.subject.service.SubjectServiceImpl$$FastClassBySpringCGLIB$$5e0a63d7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at org.shanoir.ng.subject.service.SubjectServiceImpl$$EnhancerBySpringCGLIB$$85988552.createAutoIncrement(<generated>)
	at org.shanoir.ng.subject.controler.SubjectApiController.saveNewSubject(SubjectApiController.java:121)

**Comment by jcomedouteau** [comment]
Hi Michael,
I'll have a look on what we can do !
Jean-Côme

**Comment by michaelkain** [comment]
Thank you Jean-Come!

**Comment by jcomedouteau** [comment]
where answer like '%[0-9]%'
REGEXP '^[0-9]+$';

**Comment by jcomedouteau** [comment]
SubjectRepository

**Comment by jcomedouteau** [comment]
Seems to be working:
![image](https://user-images.githubusercontent.com/7604176/148408822-8ffd462d-abbc-460d-bd0b-5a75e080fc59.png)
