### ISSUE TITLE
Tree broken for a certain study

### ISSUE THREAD

**Issue by julien-louis** [fli-iam/shanoir-ng#1213]
In qualif, as a user, member of study 94

In the tree, when I click on a subject the front calls this API : findExaminationsBySubjectIdStudyId
Here it fails with 

java.lang.NullPointerException: null
	at org.shanoir.ng.study.rights.StudyRightsService.hasRightOnStudy(StudyRightsService.java:46)
	at org.shanoir.ng.dataset.security.DatasetSecurityService.hasRightOnStudy(DatasetSecurityService.java:83)

Here is the code : 

```
StudyUser founded = repo.findByUserIdAndStudyId(userId, studyId);
return
		founded.getStudyUserRights() != null
		&& founded.getStudyUserRights().contains(StudyUserRight.valueOf(rightStr))
		&& founded.isConfirmed();
```

Seems like founded is null.
(ok there should be a null check for 'founded' here and in many other places in this class)

The database is ok : 

```> select * from study_user where study_id = 94 and user_id = 360;
+------+---------------------------+---------------------------+----------+---------+-----------+-----------+
| id   | receive_study_user_report | receive_new_import_report | study_id | user_id | user_name | confirmed |
+------+---------------------------+---------------------------+----------+---------+-----------+-----------+
| 1965 |                           |                           |       94 |     360 | jlouis    |          |
+------+---------------------------+---------------------------+----------+---------+-----------+-----------+
1 row in set (0.001 sec)
```

There is no problem with other studies.
I don't understand why it's null.

**Comment by Nunien** [comment]
Ok, in ExaminationApiController::findExaminationsBySubjectIdStudyId , "related" examinations are added to the response. The code look into the studyId property of Dataset and get examinations from that study.
In our study, this is the case. Datasets are linked to another study (138) but the user can't access it and that's why the StudyUser object is null.

```
mysql@shanoir-2016 qualif-datasets> select dataset.id, dataset.study_id from dataset where dataset.id in (select dataset_id from related_datasets where study_id = 94);
+--------+----------+
| id     | study_id |
+--------+----------+
| 243864 |      138 |
| 243863 |      138 |
| 243596 |      138 |
| 243583 |      138 |
| 243410 |      138 |
| 243409 |      138 |
| 243385 |      138 |
| 243384 |      138 |
| 243270 |      138 |
| 243269 |      138 |
| 243862 |      138 |
| 243593 |      138 |
| 243413 |      138 |
| 243383 |      138 |
| 243268 |      138 |
| 243866 |      138 |
| 243865 |      138 |
| 243589 |      138 |
| 243584 |      138 |
| 243412 |      138 |
| 243411 |      138 |
| 243387 |      138 |
| 243386 |      138 |
| 243272 |      138 |
| 243271 |      138 |
| 243861 |      138 |
| 243860 |      138 |
| 243587 |      138 |
| 243586 |      138 |
| 243408 |      138 |
| 243407 |      138 |
| 243382 |      138 |
| 243381 |      138 |
| 243267 |      138 |
| 243266 |      138 |
+--------+----------+
35 rows in set (0.001 sec)
```

I'm gonna commit a null check to prevent that. To unlock Malo I'm gonna give him access to that other study since it seem to belong to empenn.

Also we should maybe discuss (again!) the studyId property of Dataset.
