### ISSUE TITLE
[NG-2022-3] Auto Detection MR Sequences

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1280]
RC has developed a tool, that can detect MS related organs
and sequences automatically. The idea is to integrate this tool into Shanoir.

**Comment by michaelkain** [comment]
- one call per exam to import into shanoir
- PyInstaller: create a binary for Linux, executable to call, integration of executable into shanoir, same as today for nifti-conversion, but much more memory consumption
- PyTorch + TensorFlow, CPU version: **less than 3 Gb for binary**,
  2,6 Gb DLL are very big, contains cuda DLL and everything
- **6-800 Mb memory usage for one exam**, done serie by serie

**Comment by michaelkain** [comment]
Actually I came to the conclusion yesterday, that it might even be better in any case to run it
in the background on all existing data, even for memory and disk space consumption reasons.
(we will have to internally download the dicoms and run the detection on them for the entire exam)
We could have a background process running, that runs the auto-detection tool on each exam,
or a given list of exam ids, and so we have only one detection running on one exam at a time.

The detection process would have to be run manually or by a scheduled date. For us, we require a stable running server
to access to the data and import new ones. If we auto-detect and update the meta-data in shanoir db today
or in one week does not make a difference for us, I would say.

So, we will not depend on the actual amount of ongoing imports, the imports will remain quite small and fast, what I prefer.

We could use the same mechanism for future quality pipelines or checks we would like to run on the entire database for specific studies.

**Comment by michaelkain** [comment]
Concerning the **output.json**:

**series** : Key of the object at the root of the JSON. Contains the list of identified series with ID corresponding to the list of input series

Object **serie** :

id : Correspond à l’id en entrée == dataset acquisition ID of the exam to process
nothing to do with it

burnedInAnnotation : Vrai si la série contient des volumes pouvant identifier le patient
if true: log a warning into the log file, that this serie needs to be deleted from the database

coil : Type de bobine

contrast : Contrast de l’IRM (T1, T2, T2*, T2 DP)

deviceConstructor : Fabricant de l’IRM 
deviceMagneticField : Champ magnétique utilisé en Tesla 
deviceModel : Model de l’IRM
deviceSerialNumber : Numéro de série de l’IRM

identifier : DICOM series UUID

modality : Modalité de l’acquisition

name : Nom brute de la série

numberOfDirections : Nombre de directions d’acquisitions

originalSerieId : Id de la série dont dérive cette série (null si série originale)

protocolValidityStatus : Vrai si la série est conforme au protocol OFSEP, faux sinon.

serieNumber : Numéro de la série

type : Type standardisé de la série

**volumes** : List of volume objects composing the series

**Comment by michaelkain** [comment]
Concerning the input.json:
series: [{id: xx, files: [path, path, path]}, {}]

**Comment by youennmerel** [comment]
First step : 
- implement a new export by examination id in dataset microservice
- generate input.json as specified
- integrate input.json to the new examination export
- bonus: replace existing front-side method that currently build an examination export from multiple call to export by dataset id

**Comment by youennmerel** [comment]
@michaelkain please see https://github.com/fli-iam/shanoir-ng/pull/1571

**Comment by youennmerel** [comment]
Step 2 :
Modify import method exposed by `/importer/import_dicom/` endpoint (import MS) 
- Take into account an optional output.json
- Map output `serie.type`  into `MrProtocolMetadata.mrSequenceName`
- Map output `serie.volume.type`  into `DatasetMetadata.name`
  > the generated volumes by the tool, will have to be mapped to corresponding datasets, generated by Shanoir during the import, so we will have to find the right dataset for the right volume

**Comment by youennmerel** [comment]
As discussed in weekly meeting :
- import only output.json on a new, dedicated webservice
-  directly update existing dataset (no new Processed dataset to create)

**Comment by youennmerel** [comment]
@michaelkain we need to identify the dicom metadata we can use to find the corresponding datasets.

For example, are `acquisitionDate` and `acquistionTime` associated with DatasetAcquistion or Dataset in DICOM ?

**Comment by youennmerel** [comment]
@youennmerel : Test with input.id = dataset.id

**Comment by youennmerel** [comment]
> @youennmerel : Test with input.id = dataset.id

@michaelkain

As the qualif & prod massive download APIs are down for the moment, I've tested it on my dev.

With acquisitionId as serie.id in input.json, the execution is OK and an output.json is produced.

With datasetId as serie.id in input.json, the execution fail with the following error :
``` python
Traceback (most recent call last):
  File "main.py", line 37, in <module>
  File "main.py", line 33, in mainWParseArguments
  File "main.py", line 24, in main
  File "identifier.py", line 242, in identify
  File "helpers/volume.py", line 339, in getStandardizedType
  File "models/volumeModel.py", line 80, in getSiblings
  File "models/serieModel.py", line 58, in getChildren
TypeError: 'NoneType' object is not subscriptable
[211596] Failed to execute script 'main' due to unhandled exception!
```

**Comment by youennmerel** [comment]
@youennmerel :
- specify the list of new variables from Kitware pipeline that must be stored in shanoir
- specify a new table in datasets database to store calculated "scores" from pipelines

**Comment by youennmerel** [comment]
Hi @michaelkain, 

After discussions with @jcomedouteau, here's my proposition for the new table :

### dataset_properties
| Field | Type | Comment |
| ----------- | ----------- | ----------- |
| dataset_properties_id | bigint | PK | 
| dataset_id | bigint | FK (dataset) | 
| dataset_processing_id | bigint | FK (dataset_processing) | 
| name | varchar | Name of property (e.g. `organAlgo`) | 
| value | varchar | Value of property (e.g. `brain`) |

**Comment by michaelkain** [comment]
Dear Youenn (@youennmerel), I fully agree on the schema above to start with, thank you!
