### ISSUE TITLE
Pathology model specification file download fails

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1318]
java.lang.NullPointerException: null
	at java.base/java.io.File.<init>(File.java:278)
	at org.shanoir.ng.preclinical.pathologies.pathology_models.PathologyModelApiController.downloadModelSpecifications(PathologyModelApiController.java:239)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by jcomedouteau** [comment]
Everything is broken with pathology model specification
- Add download button on detail
- Allow to remove a file
- File is not correctly created
- File is not correctly retrieved using the correct path

We need to take some time on this OR juste remove this feature.
