### ISSUE TITLE
Qualif: blocking issue: imports on error (tested with ShUp)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1610]
Caused by: org.shanoir.ng.shared.exception.ShanoirException: Unexpected error during the import: null, please contact an administrator.
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:241)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createAllDatasetAcquisitions(DatasetAcquisitionApiController.java:128)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createNewDatasetAcquisition(DatasetAcquisitionApiController.java:114)
	... 33 common frames omitted
**Caused by: java.lang.NullPointerException: null
	at org.shanoir.ng.studycard.model.condition.StudyCardDICOMCondition.fulfilled(StudyCardDICOMCondition.java:100)
	at org.shanoir.ng.studycard.model.condition.StudyCardDICOMCondition.fulfilled(StudyCardDICOMCondition.java:50)**
	at org.shanoir.ng.studycard.model.rule.DatasetAcquisitionRule.conditionsfulfilled(DatasetAcquisitionRule.java:52)
	at org.shanoir.ng.studycard.model.rule.DatasetAcquisitionRule.apply(DatasetAcquisitionRule.java:43)
	at org.shanoir.ng.studycard.model.StudyCard.apply(StudyCard.java:154)
	at org.shanoir.ng.importer.strategies.datasetacquisition.MrDatasetAcquisitionStrategy.generateDatasetAcquisitionForSerie(MrDatasetAcquisitionStrategy.java:149)
	at org.shanoir.ng.importer.service.DatasetAcquisitionContext.generateDatasetAcquisitionForSerie(DatasetAcquisitionContext.java:67)
	at org.shanoir.ng.importer.service.ImporterService.createDatasetAcquisitionForSerie(ImporterService.java:324)
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:180)
	... 35 common frames omitted

**Comment by michaelkain** [comment]
Hi Julien (@julien-louis) I hope you are doing fine. I have copied the stack trace above. My imports with ShUp do not work anymore on qualif. It looks like an issue with StudyCards, that might be related to your quality card changes. Thank you and with kind regards, Michael

**Comment by julien-louis** [comment]
@michaelkain , I fixed it on develop and deployed it in qualif, could you test it ?

**Comment by michaelkain** [comment]
FIXED, tested on qualif
