### ISSUE TITLE
[Quality Control] - review

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#1617]
- Remove "re-apply study card" button from quality control detail.
- Edit study - select quality tab, no quality card existing, Click on Edit study, the screen is "empty": propose a button "create quality card"
- Rename quality report to "error report" and be clear, that valid results are not in report

**Comment by jcomedouteau** [comment]
java.lang.NullPointerException: null
	at org.shanoir.ng.dataset.security.DatasetSecurityService.hasRightOnSubjectStudies(DatasetSecurityService.java:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:139)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:139)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:55)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:386)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:188)
	at org.springframework.expression.spel.ast.OpOr.getBooleanValue(OpOr.java:56)
	at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:47)
	at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:37)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:188)
	at org.springframework.expression.spel.ast.OpAnd.getBooleanValue(OpAnd.java:57)
	at org.springframework.expression.spel.ast.OpAnd.getValueInternal(OpAnd.java:52)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:188)
	at org.springframework.expression.spel.ast.OpOr.getBooleanValue(OpOr.java:56)
	at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:51)
	at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:37)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:309)
	at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:30)
	at org.springframework.security.access.expression.method.ExpressionBasedPreInvocationAdvice.before(ExpressionBasedPreInvocationAdvice.java:51)
	at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:71)
	at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:42)
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:60)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.attemptAuthorization(AbstractSecurityInterceptor.java:239)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:208)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at org.shanoir.ng.shared.service.SubjectStudyServiceImpl$$EnhancerBySpringCGLIB$$e4e894d1.update(<generated>)
	at org.shanoir.ng.studycard.service.CardsProcessingService.applyQualityCardOnStudy(CardsProcessingService.java:119)
	at org.shanoir.ng.studycard.controler.QualityCardApiController.applyQualityCardOnStudy(QualityCardApiController.java:160)
	at org.shanoir.ng.studycard.controler.QualityCardApiController$$FastClassBySpringCGLIB$$9cc1dd3.invoke(<generated>)

**Comment by jcomedouteau** [comment]
Rajouter un bouton de création de quality card depuis le détail de l'étude

**Comment by michaelkain** [comment]
Hi, maybe it would be interesting, when a DICOM tag is used as condition for quality cards and an error occurs to display the DICOM tag name, instead of the tag integer number (see screenshot 00185,100), that the user better knows, what is wrong.
![Screenshot from 2023-03-31 15-06-00](https://user-images.githubusercontent.com/4560288/229128821-8f3092bf-3fcc-4890-b52f-7c977309831a.png)

**Comment by jcomedouteau** [comment]
Get the warning / flags in the study detail tree

**Comment by jcomedouteau** [comment]
Remove  logs:
ng.download.WADODownloaderService    : get DICOM attributes for dataset 418939 : 104 ms
2023-03-31 15:21:13.789 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for acquisition 231408 : 108 ms
2023-03-31 15:21:13.941 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for dataset 418967 : 146 ms
2023-03-31 15:21:13.941 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for acquisition 231414 : 151 ms
2023-03-31 15:21:13.942  WARN 1 --- [io-9904-exec-10] o.s.n.s.m.rule.QualityExaminationRule    : No subject study in exam 16694
2023-03-31 15:21:14.022 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for dataset 418995 : 74 ms
2023-03-31 15:21:14.022 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for acquisition 231420 : 79 ms
2023-03-31 15:21:14.169 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for dataset 419023 : 141 ms
2023-03-31 15:21:14.169 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for acquisition 231426 : 146 ms
2023-03-31 15:21:14.324 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for dataset 419134 : 150 ms
2023-03-31 15:21:14.325 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for acquisition 231486 : 155 ms
2023-03-31 15:21:14.411 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for dataset 419162 : 80 ms
2023-03-31 15:21:14.411 ERROR 1 --- [io-9904-exec-10] o.s.ng.download.WADODownloaderService    : get DICOM attributes for acqu
