### ISSUE TITLE
Import from PACS or ZIP fail with "No enum constant org.shanoir.ng.datasetacquisition.model.mr.MrSequenceVariant./SS"

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#1746]
![image](https://github.com/fli-iam/shanoir-ng/assets/59697998/8f7c66b7-e5e5-4c90-a16e-0fe87011cee0)

```java
2023-06-08 10:26:30.616  INFO 1 --- [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#12-1] o.s.n.i.s.d.MrDatasetAcquisitionStrategy : Generating DatasetAcquisition for   : cmrr_mbep2d_diff - Diff cusp66 b3000 AP 2mm preacq
norm - Rank:13
2023-06-08 10:26:30.636 ERROR 1 --- [org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#12-1] o.s.ng.importer.service.ImporterService  : Error during import for exam: 19902 : {}

java.lang.IllegalArgumentException: No enum constant org.shanoir.ng.datasetacquisition.model.mr.MrSequenceVariant./SS
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.shanoir.ng.datasetacquisition.model.mr.MrSequenceVariant.valueOf(MrSequenceVariant.java:23)
	at org.shanoir.ng.datasetacquisition.model.mr.MrSequenceVariant.getIdByType(MrSequenceVariant.java:95)
	at org.shanoir.ng.datasetacquisition.model.mr.MrProtocolMetadata.setMrSequenceVariant(MrProtocolMetadata.java:283)
	at org.shanoir.ng.importer.strategies.protocol.MrProtocolStrategy.createOriginMrProtocolMetadata(MrProtocolStrategy.java:380)
	at org.shanoir.ng.importer.strategies.protocol.MrProtocolStrategy.generateProtocolForSerie(MrProtocolStrategy.java:59)
	at org.shanoir.ng.importer.strategies.datasetacquisition.MrDatasetAcquisitionStrategy.generateDatasetAcquisitionForSerie(MrDatasetAcquisitionStrategy.java:115)
	at org.shanoir.ng.importer.service.DatasetAcquisitionContext.generateDatasetAcquisitionForSerie(DatasetAcquisitionContext.java:63)
	at org.shanoir.ng.importer.service.ImporterService.createDatasetAcquisitionForSerie(ImporterService.java:196)
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:131)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createAllDatasetAcquisitions(DatasetAcquisitionApiController.java:132)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createNewDatasetAcquisition(DatasetAcquisitionApiController.java:118)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController$$FastClassBySpringCGLIB$$a9e2eff7.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController$$EnhancerBySpringCGLIB$$3ce94728.createNewDatasetAcquisition(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
	at org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:75)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:261)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandlerAndProcessResult(MessagingMessageListenerAdapter.java:207)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:146)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1665)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1584)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1572)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1563)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1507)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:967)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:914)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:83)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1291)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1197)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jcomedouteau** [comment]
Je suis en pleine réflexion. L'erreur est quand même assez claire, c'est ce qu'il y a dans les données qui parait assez pourri.
On peut rajouter un "unknown" dans l'enum, mais on va clairement pas rajouter un "/SS" dedans, ca n'a pas beaucoup de sens.
Faudrait savoir d'où les données viennent et comment ca a pu se retrouver comme ça..
