### ISSUE TITLE
Jobs table: wrong link in error case

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1806]
the URL ends with "**examinations/5, please contact an administrator**"

Uncaught (in promise): lC: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"OK","url":"https://shanoir-ng-nginx/shanoir-ng/datasets/examinations/**NaN**","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://shanoir-ng-nginx/shanoir-ng/datasets/examinations/NaN: 500 OK","error":{"code":500,"message":"Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; For input string: \"NaN\"","details":null}}

![image](https://github.com/fli-iam/shanoir-ng/assets/4560288/016f596a-6925-410b-a273-040bff0e7021)

**Comment by michaelkain** [comment]
and in the backend:
Caused by: java.lang.NumberFormatException: For input string: "NaN"

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:711)
	at java.base/java.lang.Long.valueOf(Long.java:1163)
	at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:206)

	at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:115)
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:429)
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:402)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:155)
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:53)

	at org.springframework.validation.DataBinder.convertIfNecessary(DataBinder.java:729)

	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver
	.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:125)
