### ISSUE TITLE
Wrong study card blocks import

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#1915]
Hi Julien, this issue, is a quite important one, and annoying for our users, that actually do the imports.
We can not allow a wrong study card to block imports, this should be changed please.

**Comment by michaelkain** [comment]
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener method 'public void org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createNewDatasetAcquisition(org.springframework.amqp.core.Message) throws com.fasterxml.jackson.core.JsonParseException,com.fasterxml.jackson.databind.JsonMappingException,java.io.IOException,org.springframework.amqp.AmqpRejectAndDontRequeueException' threw exception
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:286)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandlerAndProcessResult(MessagingMessageListenerAdapter.java:224)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:149)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1660)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1579)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1567)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1558)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListenerAndHandleException(AbstractMessageListenerContainer.java:1503)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.lambda$executeListener$8(AbstractMessageListenerContainer.java:1481)
	at io.micrometer.observation.Observation.lambda$observe$0(Observation.java:493)
	at io.micrometer.observation.Observation.observeWithContext(Observation.java:603)
	at io.micrometer.observation.Observation.observe(Observation.java:492)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1481)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:994)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:941)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1323)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1225)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.springframework.amqp.AmqpRejectAndDontRequeueException: null
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createNewDatasetAcquisition(DatasetAcquisitionApiController.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController$$SpringCGLIB$$0.createNewDatasetAcquisition(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
	at org.springframework.amqp.rabbit.listener.adapter.KotlinAwareInvocableHandlerMethod.doInvoke(KotlinAwareInvocableHandlerMethod.java:45)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
	at org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:75)
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:277)
	... 17 common frames omitted
Caused by: org.shanoir.ng.shared.exception.ShanoirException: Unexpected error during the import: No enum constant org.shanoir.ng.dataset.model.DatasetModalityType.MR, please contact an administrator.
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:207)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createAllDatasetAcquisitions(DatasetAcquisitionApiController.java:136)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createNewDatasetAcquisition(DatasetAcquisitionApiController.java:121)
	... 41 common frames omitted
Caused by: java.lang.IllegalArgumentException: No enum constant org.shanoir.ng.dataset.model.DatasetModalityType.MR
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.shanoir.ng.dataset.model.DatasetModalityType.valueOf(DatasetModalityType.java:23)
	at org.shanoir.ng.studycard.model.field.DatasetMetadataField$1.update(DatasetMetadataField.java:44)
	at org.shanoir.ng.studycard.model.field.DatasetMetadataField$1.update(DatasetMetadataField.java:31)
	at org.shanoir.ng.studycard.model.assignment.DatasetAssignment.apply(DatasetAssignment.java:57)
	at org.shanoir.ng.studycard.model.rule.DatasetAcquisitionRule.applyAssignments(DatasetAcquisitionRule.java:66)
	at org.shanoir.ng.studycard.model.rule.DatasetAcquisitionRule.apply(DatasetAcquisitionRule.java:42)
	at org.shanoir.ng.studycard.model.StudyCard.apply(StudyCard.java:151)
	at org.shanoir.ng.importer.service.ImporterService.generateAcquisitions(ImporterService.java:233)
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:132)
	... 43 common frames omitted

**Comment by michaelkain** [comment]
![Screenshot from 2023-10-23 11-57-19](https://github.com/fli-iam/shanoir-ng/assets/4560288/c94cc8e7-0b9b-4cc9-b3ce-3f7aa46617dc)
