### ISSUE TITLE
ShUp: Neurinfo: issue with query/retrieve pacs

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#2016]
at Neurinfo, with the PACS Telemis and ShUp the following error occurs:
similar error, on StudyRootLevel, either with studyDescription or with studyDate

2024-01-12 16:28:20 ERROR [org.shanoir.uploader.action.FindDicomActionListener] [216] Cannot parse null string
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at org.shanoir.ng.importer.dicom.SeriesNumberSorter.compare(SeriesNumberSorter.java:13)
	at org.shanoir.ng.importer.dicom.SeriesNumberSorter.compare(SeriesNumberSorter.java:7)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at org.shanoir.ng.importer.dicom.query.QueryPACSService.querySeries(QueryPACSService.java:406)
	at org.shanoir.ng.importer.dicom.query.QueryPACSService.queryStudyLevel(QueryPACSService.java:292)
	at org.shanoir.ng.importer.dicom.query.QueryPACSService.queryCFIND(QueryPACSService.java:189)

**Comment by michaelkain** [comment]
waiting for test time in chu

**Comment by michaelkain** [comment]
solved
