### ISSUE TITLE
JDBCException at first download

### ISSUE THREAD

**Issue by julien-louis** [fli-iam/shanoir-ng#2017]
After a qualif server reset, the first dataset on the first mass download (Chrome) fails. It works on a second attempt.

The exception : 

```
qualif-datasets-1  | org.hibernate.exception.SQLGrammarException: JDBC exception executing SQL [select p1_0.dataset_id,p1_1.id,case end,p1_1.comment,p1_1.dataset_processing_type,p2_0.id,case when p2_1.id is not null then 1 when p2_0.id is not null then 0 end,p2_0.comment,p2_0.dataset_processing_type,p2_0.parent_id,p2_0.processing_date,p2_0.study_id,p2_1.end_date,p2_1.identifier,p2_1.name,p2_1.output_processing,p2_1.pipeline_identifier,p2_1.results_location,p2_1.start_date,p2_1.status,p2_1.timeout,p1_1.processing_date,p1_1.study_id,p1_2.end_date,p1_2.identifier,p1_2.name,p1_2.output_processing,p1_2.pipeline_identifier,p1_2.results_location,p1_2.start_date,p1_2.status,p1_2.timeout from input_of_dataset_processing p1_0 join (dataset_processing p1_1 left join execution_monitoring p1_2 on p1_1.id=p1_2.id) on p1_1.id=p1_0.processing_id left join (dataset_processing p2_0 left join execution_monitoring p2_1 on p2_0.id=p2_1.id) on p2_0.id=p1_1.parent_id where p1_0.dataset_id=?] [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'p1_1.comment,p1_1.dataset_processing_type,p2_0.id,case when p2_1.id is not null ' at line 1] [n/a]
qualif-datasets-1  | 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:64)
qualif-datasets-1  | 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
qualif-datasets-1  | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
qualif-datasets-1  | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)
qualif-datasets-1  | 	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:257)
qualif-datasets-1  | 	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:163)
qualif-datasets-1  | 	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:254)
qualif-datasets-1  | 	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:134)
qualif-datasets-1  | 	at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
qualif-datasets-1  | 	at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
qualif-datasets-1  | 	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:178)
qualif-datasets-1  | 	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
qualif-datasets-1  | 	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:361)
qualif-datasets-1  | 	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
qualif-datasets-1  | 	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
qualif-datasets-1  | 	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
qualif-datasets-1  | 	at org.hibernate.loader.ast.internal.CollectionLoaderSingleKey.load(CollectionLoaderSingleKey.java:115)
qualif-datasets-1  | 	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:680)
qualif-datasets-1  | 	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
qualif-datasets-1  | 	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
qualif-datasets-1  | 	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1702)
qualif-datasets-1  | 	at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$initialize$3(AbstractPersistentCollection.java:617)
qualif-datasets-1  | 	at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
qualif-datasets-1  | 	at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615)
qualif-datasets-1  | 	at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:136)
qualif-datasets-1  | 	at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$readSize$0(AbstractPersistentCollection.java:163)
qualif-datasets-1  | 	at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
qualif-datasets-1  | 	at org.hibernate.collection.spi.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:148)
qualif-datasets-1  | 	at org.hibernate.collection.spi.PersistentBag.size(PersistentBag.java:355)
qualif-datasets-1  | 	at org.shanoir.ng.dataset.modality.MrDatasetMapperImpl_.datasetProcessingListToDatasetProcessingDTOList(MrDatasetMapperImpl_.java:233)
qualif-datasets-1  | 	at org.shanoir.ng.dataset.modality.MrDatasetMapperImpl_.datasetToDatasetAndProcessingsDTO(MrDatasetMapperImpl_.java:128)
qualif-datasets-1  | 	at org.shanoir.ng.dataset.modality.MrDatasetMapperImpl.datasetToDatasetAndProcessingsDTO(MrDatasetMapperImpl.java:30)
qualif-datasets-1  | 	at org.shanoir.ng.dataset.controler.DatasetApiController.findDatasetById(DatasetApiController.java:181)
qualif-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
qualif-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
qualif-datasets-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
qualif-datasets-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
qualif-datasets-1  | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
qualif-datasets-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
qualif-datasets-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
qualif-datasets-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
qualif-datasets-1  | 	at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.invoke(AuthorizationManagerBeforeMethodInterceptor.java:199)
qualif-datasets-1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
qualif-datasets-1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
qualif-datasets-1  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
qualif-datasets-1  | 	at org.shanoir.ng.dataset.controler.DatasetApiController$$SpringCGLIB$$0.findDatasetById(<generated>)
qualif-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
qualif-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
qualif-datasets-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
qualif-datasets-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
qualif-datasets-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
qualif-datasets-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
qualif-datasets-1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
qualif-datasets-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884)
qualif-datasets-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
qualif-datasets-1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
qualif-datasets-1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081)
qualif-datasets-1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974)
qualif-datasets-1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011)
qualif-datasets-1  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
qualif-datasets-1  | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564)
qualif-datasets-1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
qualif-datasets-1  | 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
qualif-datasets-1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
qualif-datasets-1  | 	at org.shanoir.ng.dicom.web.StowRSMultipartRelatedRequestFilter.doFilter(StowRSMultipartRelatedRequestFilter.java:93)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
qualif-datasets-1  | 	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.shanoir.ng.dicom.web.StowRSMultipartRelatedRequestFilter.doFilter(StowRSMultipartRelatedRequestFilter.java:93)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
qualif-datasets-1  | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
qualif-datasets-1  | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:145)
qualif-datasets-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
qualif-datasets-1  | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
qualif-datasets-1  | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
qualif-datasets-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
qualif-datasets-1  | 	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
qualif-datasets-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
qualif-datasets-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
qualif-datasets-1  | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
qualif-datasets-1  | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
qualif-datasets-1  | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
qualif-datasets-1  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
qualif-datasets-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
qualif-datasets-1  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
qualif-datasets-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
qualif-datasets-1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
qualif-datasets-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
qualif-datasets-1  | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
qualif-datasets-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
qualif-datasets-1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
qualif-datasets-1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
qualif-datasets-1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
qualif-datasets-1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
qualif-datasets-1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
qualif-datasets-1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
qualif-datasets-1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
qualif-datasets-1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
qualif-datasets-1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
qualif-datasets-1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
qualif-datasets-1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
qualif-datasets-1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
qualif-datasets-1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
qualif-datasets-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
qualif-datasets-1  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
qualif-datasets-1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
qualif-datasets-1  | 	at java.base/java.lang.Thread.run(Thread.java:840)
qualif-datasets-1  | Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'p1_1.comment,p1_1.dataset_processing_type,p2_0.id,case when p2_1.id is not null ' at line 1
qualif-datasets-1  | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
qualif-datasets-1  | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
qualif-datasets-1  | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
qualif-datasets-1  | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
qualif-datasets-1  | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
qualif-datasets-1  | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
qualif-datasets-1  | 	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:239)
qualif-datasets-1  | 	... 141 common frames omitted
qualif-datasets-1  | 

```

**Comment by julien-louis** [comment]
this kind of error triggers the same error message, tested on qualif : 

```
mysql@shanoir-2016 qualif-datasets> select id, case when id <=5 then 'small' when id > 5 then 'big' end from dataset order by id asc limit 10;
+----+----------------------------------------------------------+
| id | case when id <=5 then 'small' when id > 5 then 'big' end |
+----+----------------------------------------------------------+
|  1 | small                                                    |
|  2 | small                                                    |
|  3 | small                                                    |
|  4 | small                                                    |
|  5 | small                                                    |
|  6 | big                                                      |
|  7 | big                                                      |
|  8 | big                                                      |
|  9 | big                                                      |
| 10 | big                                                      |
+----+----------------------------------------------------------+
10 rows in set (0,001 sec)




mysql@shanoir-2016 qualif-datasets> select id, case end from dataset order by id asc limit 10;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from dataset order by id asc limit 10' at line 1

```

**Comment by julien-louis** [comment]
complete working query

```
datasets                  |     select
datasets                  |         p1_0.dataset_id,
datasets                  |         p1_1.id,
datasets                  |         case 
datasets                  |             when p1_2.id is not null then 1 
datasets                  |             when p1_1.id is not null then 0 
datasets                  |         end,
datasets                  |         p1_1.comment,
datasets                  |         p1_1.dataset_processing_type,
datasets                  |         p2_0.id,
datasets                  |         case 
datasets                  |             when p2_1.id is not null then 1 
datasets                  |             when p2_0.id is not null then 0 
datasets                  |         end,
datasets                  |         p2_0.comment,
datasets                  |         p2_0.dataset_processing_type,
datasets                  |         p2_0.parent_id,
datasets                  |         p2_0.processing_date,
datasets                  |         p2_0.study_id,
datasets                  |         p2_1.end_date,
datasets                  |         p2_1.identifier,
datasets                  |         p2_1.name,
datasets                  |         p2_1.output_processing,
datasets                  |         p2_1.pipeline_identifier,
datasets                  |         p2_1.results_location,
datasets                  |         p2_1.start_date,
datasets                  |         p2_1.status,
datasets                  |         p2_1.timeout,
datasets                  |         p1_1.processing_date,
datasets                  |         p1_1.study_id,
datasets                  |         p1_2.end_date,
datasets                  |         p1_2.identifier,
datasets                  |         p1_2.name,
datasets                  |         p1_2.output_processing,
datasets                  |         p1_2.pipeline_identifier,
datasets                  |         p1_2.results_location,
datasets                  |         p1_2.start_date,
datasets                  |         p1_2.status,
datasets                  |         p1_2.timeout 
datasets                  |     from
datasets                  |         input_of_dataset_processing p1_0 
datasets                  |     join
datasets                  |         (dataset_processing p1_1 
datasets                  |     left join
datasets                  |         execution_monitoring p1_2 
datasets                  |             on p1_1.id=p1_2.id) 
datasets                  |                 on p1_1.id=p1_0.processing_id 
datasets                  |         left join
datasets                  |             (dataset_processing p2_0 
datasets                  |         left join
datasets                  |             execution_monitoring p2_1 
datasets                  |                 on p2_0.id=p2_1.id) 
datasets                  |                     on p2_0.id=p1_1.parent_id 
datasets                  |             where
datasets                  |                 p1_0.dataset_id=?
```
