### ISSUE TITLE
ohif-viewer: display in 3D: not working

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#2369]
Hi @pierrehenri-dauvergne,

I hope you are doing fine.

When I try to open a 3D serie with the 3D view in ohif, I get an exception in the browser console.
Please see stack trace below. There might be a relation with missing CORS tags. 

app.bundle.53f9c7bd00e09e755558.js:219996 **Uncaught (in promise) Error: SharedArrayBuffer is NOT supported in your browser see https://developer.chrome.com/blog/enabling-shared-array-buffer/**
    at createFloat32SharedArray (app.bundle.53f9c7bd00e09e755558.js:219996:15)
    at Module.generateVolumePropsFromImageIds (app.bundle.53f9c7bd00e09e755558.js:221759:23)
    at getStreamingImageVolume (5793.bundle.eed3fe9019c31999efff.js:862:120)
    at cornerstoneStreamingImageVolumeLoader (5793.bundle.eed3fe9019c31999efff.js:885:41)
    at loadVolumeFromVolumeLoader (app.bundle.53f9c7bd00e09e755558.js:218446:30)
    at Module.createAndCacheVolume (app.bundle.53f9c7bd00e09e755558.js:218481:24)
    at CornerstoneCacheService._getVolumeViewportData (5516.bundle.f61b8aebe75f7bafd5b1.js:12847:41)
    at CornerstoneCacheService.createViewportData (5516.bundle.f61b8aebe75f7bafd5b1.js:12705:33)
    at loadViewportData (1169.bundle.a3d3d310f1d8d7e335bf.js:1878:58)
    at 1169.bundle.a3d3d310f1d8d7e335bf.js:1915:5

**Comment by michaelkain** [comment]
click on MPR here to see it on 3D series and get the exception
![Screenshot from 2024-08-21 14-26-43](https://github.com/user-attachments/assets/9447260b-d40e-4c51-9b6c-5ebc8f27b05d)

**Comment by michaelkain** [comment]
second most important, as it blocks us from using segmentation and 3D view
