### ISSUE TITLE
[Talk] Handling subject and data after copy

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#2470]
Supposons qu'on a deux études (etudeA et etudeB). On fait un import dans etudeA dans lequel on créé subjectA et examA. Ensuite on copie les données importées dans etudeA vers etudeB.
Le subject reste le même mais les données copiées ont un autre identifiant.

On a donc cette situation :
![image](https://github.com/user-attachments/assets/60dae54c-db8e-4656-b27e-a0e61cb7db69)

1. Actuellement si on retire le subject de etudeB, les données ne sont pas supprimées (présentes dans solr) mais à l'ouverture l'arbre ne s'affiche pas: 
![image](https://github.com/user-attachments/assets/0f5a0ed3-f526-4600-af11-4803b5d4860e)

**Faut-il laisser ces datasets dans solr ? Ils montrent des informations fausses puisque subjectA n'appartient plus à etudeB.
Que faire dans cette situation ?**

2. Un utilisateur avec les droits admin dans etudeA mais n'ayant pas accès à etudeB peut retirer subjectA de son étude. Dans ce cas, etudeB n'est pas impactée. Même chose dans l'autre sens: un utilisateur avec les droits admin dans etudeB peut retirer subjectA de son étude, cela n'impactera pas etudeA.

L'affichage est peut-être trompeur, on a l'impression de supprimer un subject alors qu'on ne fait que le retirer de l'étude lorsqu'il a été copié.
Dans le cas où on souhaite supprimer un subject d'une étude où rien n'a été copié, cette pop-up apparait :
![image](https://github.com/user-attachments/assets/4e64edd6-e09e-4a0c-ad98-6f10f3549a9e)

Lorsqu'on clique sur "OK" puis "Update" pour mettre à jour l'étude, une erreur apparait et l'étude n'est pas mise à jour :
```
studies            | org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.ObjectDeletedException: deleted instance passed to merge: [org.shanoir.ng.studyexamination.StudyExamination#<null>]
studies            |    at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:371)
studies            |    at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:246)
studies            |    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
studies            |    at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
studies            |    at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:335)
studies            |    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
studies            |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
studies            |    at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:164)
studies            |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
studies            |    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
studies            |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
studies            |    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
studies            |    at jdk.proxy2/jdk.proxy2.$Proxy209.save(Unknown Source)
studies            |    at org.shanoir.ng.study.service.StudyServiceImpl.update(StudyServiceImpl.java:361)
```

Dans solr en revanche, les données importées ne sont plus visibles. Le subject est lui toujours disponible dans subject-list mais rien n'est dedans :
![image](https://github.com/user-attachments/assets/c26b55af-33f2-4660-930c-65d399987055)

Maintenant si je veux ré-importer dans ce même subject, en créant un nouvel exam j'ai une erreur:
```
datasets           | java.util.NoSuchElementException: No value present
datasets           |    at java.base/java.util.Optional.get(Unknown Source)
datasets           |    at org.shanoir.ng.examination.service.ExaminationServiceImpl.save(ExaminationServiceImpl.java:218)
```

3. Il était question de ne plus permettre à un subject d'appartenir à plusieurs études. Lors de copies de données, un subject appartient forcément à plusieurs études. 

Est-ce qu'on décide quelque chose ?

4. TODO ?

**Comment by pierrehenri-dauvergne** [comment]
What to test:

![image](https://github.com/user-attachments/assets/c4d5e3a1-4c9a-48e1-aee0-127f10ee71ac)

![image](https://github.com/user-attachments/assets/1560b83c-9245-4fd5-8209-edb55b90016b)

Test file: 
[Test subject remove and delete.xlsx](https://github.com/user-attachments/files/17649633/Test.subject.remove.and.delete.xlsx)

**Comment by julien-louis** [comment]
# Draft

## Delete a Dataset

* if has copies : don't delete, error msg "delete children first"
* else : 
    * if is copy : don't touch the parent
    * delete dataset
    * delete DICOM in pacs
    * delete other children entities

## Delete a Dataset Acquisition

* if has copies : don't delete, error msg "delete children first"
* else : 
    * if is copy : don't touch the parent
    * try to delete acquisition + datasets
        * if acq or dataset has copies, do nothing

## Delete an Examination

* if has copies : don't delete, error msg "delete children first"
* else : 
    * if is copy : don't touch the parent
    * try to delete examination + acquisitions (cascading datasets)
    * 

## Delete a Subject

* if subject exists in another study : delete only current subject-study (= "remove" subject from study)
* else if subject exist only in specified study : 
    * try to delete examinations (cascading acquisition, datasets, etc)
        * if error (exam/acq/ds has copies)
            * do nothing
        * else  
            * delete subject-study
            * delete subject

**Comment by julien-louis** [comment]
```
prod-n***> select count(*) from (select subject_id, count(id) as nb from studies.subject_study group by subject_id having nb > 1) dupli;
+----------+
| count(*) |
+----------+
|      308 |
+----------+
1 row in set (0,012 sec)

prod-n***> select count(*) from (select subject_id, count(id) as nb from datasets.subject_study group by subject_id having nb > 1) dupli;
+----------+
| count(*) |
+----------+
|      121 |
+----------+
1 row in set (0,009 sec)

prod-o***> select count(*) from (select subject_id, count(id) as nb from studies.subject_study group by subject_id having nb > 1) dupli;
+----------+
| count(*) |
+----------+
|     1086 |
+----------+
1 row in set (0.003 sec)

prod-o***> select count(*) from (select subject_id, count(id) as nb from datasets.subject_study group by subject_id having nb > 1) dupli;
+----------+
| count(*) |
+----------+
|      210 |
+----------+
1 row in set (0.014 sec)

```

**Comment by michaelkain** [comment]
Hi @pierrehenri-dauvergne, I hope you are doing fine. Where are we with this issue?

**Comment by pierrehenri-dauvergne** [comment]
Hi @michaelkain, we decided by vote to make it so that a subject can belong to only one study. By doing that, we should prevent some issue talked above. This work hasn't been started yet
