### ISSUE TITLE
Missing value in ParallelAcquisitionTechnique

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#262]
In some data, for Parallel acquisition technique MBSENSE is set instead of M_SENSE. This leads to:
```
java.lang.IllegalArgumentException: No enum constant org.shanoir.ng.datasetacquisition.model.mr.ParallelAcquisitionTechnique.MBSENSE
	at org.shanoir.ng.datasetacquisition.model.mr.ParallelAcquisitionTechnique.valueOf(ParallelAcquisitionTechnique.java:23)
	at org.shanoir.ng.datasetacquisition.model.mr.ParallelAcquisitionTechnique.getIdByTechnique(ParallelAcquisitionTechnique.java:82)
```
Correct ParallelAcquisitionTechnique to be able to load the data.

**Comment by michaelkain** [comment]
Is this done in your branch or still open?

**Comment by jcomedouteau** [comment]
It is done in my branch

**Comment by pierrehenri-dauvergne** [comment]
Re-open this issue because there are existing data on shanoir that can't be open due to its metadata (issue with parallel acquisition technique) :
![image](https://user-images.githubusercontent.com/117283961/225026096-9ca7fadf-5a42-417d-b711-1e4fd95e4fdc.png)

**Comment by michaelkain** [comment]
Solved
