### ISSUE TITLE
duplicate study<->subject relation in prod

### ISSUE THREAD

**Issue by a-ba** [fli-iam/shanoir-ng#329]
the migration fails because the new table `subject_study` has a unique constraint on the pair `(study_id, subject_id)`

```
Import subject_study: start
Traceback (most recent call last):
  File "./2_studies_migration.py", line 278, in <module>
    targetCursor.executemany(query, sourceCursor.fetchall())
   ...
  File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, u"Duplicate entry '153-8584' for key 'study_subject_idx'")
```

```
MySQL [shanoirdb]> select * from  REL_SUBJECT_STUDY where STUDY_ID=153 and SUBJECT_ID=8584;
+----------------------+------------------------+--------------------------+---------------------+----------+------------+
| REL_SUBJECT_STUDY_ID | IS_PHYSICALLY_INVOLVED | SUBJECT_STUDY_IDENTIFIER | REF_SUBJECT_TYPE_ID | STUDY_ID | SUBJECT_ID |
+----------------------+------------------------+--------------------------+---------------------+----------+------------+
|                 8866 |                       |                          |                   2 |      153 |       8584 |
|                 8895 |                       | asdfasdf-si              |                   2 |      153 |       8584 |
+----------------------+------------------------+--------------------------+---------------------+----------+------------+
```

**Comment by michaelkain** [comment]
Dear Anthony, to solve this issue immediately you can delete the row 8895 -> it is the result of a test run with ShanoirUploader v6.0.3 from me, so the data are not important. I will have to fix it within ShanoirUploader, that this will not happen again, but not sure if I will fix this for sh-old before the go-live... And Ofsep is not using this, so no pressure from production side... ShUp Profile Neurinfo can edit rel_subject_study and there seems to be a bug with an existing rel: it creates a new one instead of updating the old, sorry.

**Comment by michaelkain** [comment]
considered as solved
