### ISSUE TITLE
Qualif: Import Bruker not working: missing access to bruker2dicom

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#359]
Caused by: java.net.UnknownHostException: qualif-preclinical-bruker2dicom: Name does not resolve
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)

**Comment by michaelkain** [comment]
solved by Anthony
