### ISSUE TITLE
Qualif: ms users is not available anymore

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#364]
503 - Service Temporarily Unavailable

**Comment by jcomedouteau** [comment]
I'll need the users's container logs !

**Comment by michaelkain** [comment]
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [creation_date] in table [users]; found [datetime (Types#TIMESTAMP)], but expecting [date (Types#DATE)]
	at org.hibernate.tool.schema.internal.SchemaValidatorImpl.validateColumnType(SchemaValidatorImpl.java:105)
	at org.hibernate.tool.schema.internal.SchemaValidatorImpl.validateTable(SchemaValidatorImpl.java:92)
	at org.hibernate.tool.schema.internal.SchemaValidatorImpl.doValidation(SchemaValidatorImpl.java:50)
	at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:91)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:475)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:444)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:879)
	... 30 common frames omitted

**Comment by michaelkain** [comment]
Hi Anthony,
as you seem to use different migration scripts than we have, the bug seems to be in your revert from yesterday:
https://github.com/a-ba/shanoir-ng/blob/qualif/docker-compose/migration_scripts/Neurinfo/1_users_migration.py

**Comment by michaelkain** [comment]
00:00:01 + cd /tmp
00:00:01 + export HOME=/tmp
00:00:01 + HOME=/tmp
00:00:01 + svn export https://github.com/a-ba/shanoir-ng/branches/qualif/docker-compose/migration_scripts/Neurinfo migration
00:00:04 A    migration
00:00:04 A    migration/1_users_migration.py
00:00:04 A    migration/2_studies_migration.py
00:00:04 A    migration/3_import_migration.py
00:00:04 A    migration/4_datasets_migration.py
00:00:04 A    migration/dbutils.py
00:00:04 Exported revision 2926.

**Comment by jcomedouteau** [comment]
Table users locally:
| creation_date                       | date         | YES  |     | NULL    |                |
| expiration_date                     | date         | YES  |     | NULL    |                |
| extension_date                      | date         | YES  |     | NULL    |                |
| last_login                          | date         | YES  |     | NULL    |                |

DATE - format YYYY-MM-DD
DATETIME - format: YYYY-MM-DD HH:MI:SS
TIMESTAMP - format: YYYY-MM-DD HH:MI:SS
YEAR - format YYYY or YY

C'est à priori des dates partout en base (donc date uniquement sans time pour le SQL)

Shanoir old
	/** Date of creation. */
	@Column(name = "CREATED_ON", nullable = false, updatable = false)
	private Date createdOn = new Date();

Shanoir - NG
	@VisibleOnlyBy(roles = { "ROLE_ADMIN" })
	@LocalDateAnnotations
	private LocalDate creationDate;

Donc coté old on a du Date (date + time) et dans ng on a du LocalDate (juste date, pas de time).
La migration doit créer une table avec du DATETIME, mais ca ne correspond pas avec ce qu'il y a dans le code => le container ne se lance pas vu qu'il n'est pas en phase avec la BDD.

**Comment by michaelkain** [comment]
Hi Anthony, thank you for your pull request. Does your deploy script now take into consideration the sql from the main repository "develop", that we can redeploy and have ms users running? to close that issue?

**Comment by michaelkain** [comment]
fixed by Anthony, worked yesterday
