### ISSUE TITLE
Qualif: imports not working (dicom zip + pacs)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#373]
User type: user, account mkain: no import is working
Usage of DemoStudyCard number 370
Import from Dicom Zip, sampe.zip taken (existing subject and existing exam taken)
Import now clicked

- Unexpected error during the import: No enum constant org.shanoir.ng.dataset.model.DatasetModalityType.MR Dataset, please contact an administrator.

**Comment by michaelkain** [comment]
Caused by: org.shanoir.ng.shared.exception.ShanoirException: Unexpected error during the import: No enum constant org.shanoir.ng.dataset.model.DatasetModalityType.MR Dataset, please contact an administrator.
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:177)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createAllDatasetAcquisitions(DatasetAcquisitionApiController.java:110)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createNewDatasetAcquisition(DatasetAcquisitionApiController.java:97)
	... 30 common frames omitted
Caused by: java.lang.IllegalArgumentException: No enum constant org.shanoir.ng.dataset.model.DatasetModalityType.MR Dataset
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.shanoir.ng.dataset.model.DatasetModalityType.valueOf(DatasetModalityType.java:23)
	at org.shanoir.ng.studycard.model.AssignmentField$1.update(AssignmentField.java:37)
	at org.shanoir.ng.studycard.service.StudyCardProcessingService.applyAssignment(StudyCardProcessingService.java:154)
	at org.shanoir.ng.studycard.service.StudyCardProcessingService.applyAssignments(StudyCardProcessingService.java:148)
	at org.shanoir.ng.studycard.service.StudyCardProcessingService.applyStudyCardRule(StudyCardProcessingService.java:52)
	at org.shanoir.ng.studycard.service.StudyCardProcessingService.applyStudyCard(StudyCardProcessingService.java:44)
	at org.shanoir.ng.importer.strategies.datasetacquisition.MrDatasetAcquisitionStrategy.generateDatasetAcquisitionForSerie(MrDatasetAcquisitionStrategy.java:121)
	at org.shanoir.ng.importer.service.DatasetAcquisitionContext.generateDatasetAcquisitionForSerie(DatasetAcquisitionContext.java:57)
	at org.shanoir.ng.importer.service.ImporterService.createDatasetAcquisitionForSerie(ImporterService.java:189)
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:119)
	... 32 common frames omitted

**Comment by michaelkain** [comment]
StudyCard migration problem

**Comment by michaelkain** [comment]
first error: NumberFormatException, parseLong in both coil methods

**Comment by Nunien** [comment]
The import works now on qualif. Later we should try to understand why it failed.

**Comment by Nunien** [comment]
I think all work now (including pacs)
