### ISSUE TITLE
Qualif: nightly build down: error with migration script 2_studies_migration.py: duplicate entries for centers

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#375]
00:00:07 Import centers: start
00:00:07 Traceback (most recent call last):
00:00:07   File "./2_studies_migration.py", line 147, in <module>
00:00:07     targetCursor.executemany(query, sourceCursor.fetchall())
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 197, in executemany
00:00:07     self._get_db().encoding)
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 234, in _do_execute_many
00:00:07     rows += self.execute(sql + postfix)
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 170, in execute
00:00:07     result = self._query(query)
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/cursors.py", line 328, in _query
00:00:07     conn.query(q)
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 517, in query
00:00:07     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 732, in _read_query_result
00:00:07     result.read()
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1075, in read
00:00:07     first_packet = self.connection._read_packet()
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 684, in _read_packet
00:00:07     packet.check_error()
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/protocol.py", line 220, in check_error
00:00:07     err.raise_mysql_exception(self._data)
00:00:07   File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
00:00:07     raise errorclass(errno, errval)
00:00:07 pymysql.err.IntegrityError: (1062, u"Duplicate entry '1' for key 'PRIMARY'")

**Comment by michaelkain** [comment]
qualif up, fixed
