### ISSUE TITLE
First connection in Shanoir never finishes 

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#394]
Due to an offline rights test done in LastLoginApi, first connection on the server never finishes:

> users                       | org.springframework.security.access.AccessDeniedException: Access is denied
> users                       |   at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
> users                       |   at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
> users                       |   at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
> users                       |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
> users                       |   at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
> users                       |   at org.shanoir.ng.user.service.UserServiceImpl$$EnhancerBySpringCGLIB$$7ead604c.updateLastLogin(<generated>)
> users                       |   at org.shanoir.ng.user.controller.LastLoginDateApiController.lastLoginDate(LastLoginDateApiController.java:46)

To correct this, remove rights check in UserService.updateLastLogin which is called by LastLoginDateApiController which is called directly from keycloak.

**Comment by jcomedouteau** [comment]
I feel like this correction does not work for the moment. To be checked.

**Comment by jcomedouteau** [comment]
Never had this problem anymore. Closing this.
