### ISSUE TITLE
ShUp: with qualif (sh-ng): exam creation: access denied

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#415]
![Bildschirmfoto 2020-07-31 um 15 21 59](https://user-images.githubusercontent.com/4560288/89040428-11515080-d344-11ea-906e-1d5404732b56.png)

org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.shanoir.ng.examination.controler.ExaminationApiController$$EnhancerBySpringCGLIB$$24e2dc6c.saveNewExamination(<generated>)

**Comment by michaelkain** [comment]
![Bildschirmfoto 2020-07-31 um 15 52 34](https://user-images.githubusercontent.com/4560288/89041850-57a7af00-d346-11ea-894d-52110f2ef66d.png)
this change is the reason, refactor in shup

**Comment by michaelkain** [comment]
fixed
