### ISSUE TITLE
ShUp: with qualif (sh-ng): errors with imports

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#417]
- using ShUp to import data
- files are uploaded, error when starting import:

org.springframework.security.access.AccessDeniedException: Access is denied

	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.shanoir.ng.importer.ImporterApiController$$EnhancerBySpringCGLIB$$ca4d46f9. **startImportJob**(<generated>)

**Comment by michaelkain** [comment]
first bug solved, second too come:
2020-08-03 08:52:01.022 ERROR 1 --- [AsyncThread-2] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected error occurred invoking async method 'public void org.shanoir.ng.importer.ImporterManagerService.manageImportJob(java.lang.Long,org.springframework.http.HttpHeaders,org.shanoir.ng.importer.model.ImportJob)'.

java.lang.NullPointerException: null
	at org.shanoir.ng.importer.dcm2nii.DatasetsCreatorAndNIfTIConverterService.moveFiles(DatasetsCreatorAndNIfTIConverterService.java:807)
	at org.shanoir.ng.importer.dcm2nii.DatasetsCreatorAndNIfTIConverterService.createSerieIDFolderAndMoveFiles(DatasetsCreatorAndNIfTIConverterService.java:795)
	at org.shanoir.ng.importer.dcm2nii.DatasetsCreatorAndNIfTIConverterService.createDatasetsAndRunConversion(DatasetsCreatorAndNIfTIConverterService.java:152)
	at org.shanoir.ng.importer.dcm2nii.DatasetsCreatorAndNIfTIConverterService$$FastClassBySpringCGLIB$$90ba23a2.invoke(<generated>)

**Comment by michaelkain** [comment]
next bug coming up:
Caused by: org.shanoir.ng.shared.exception.ShanoirException: Unexpected error during the import: Validation failed for classes [org.shanoir.ng.datasetacquisition.model.mr.MrDatasetAcquisition] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='may not be null', propertyPath=acquisitionEquipmentId, rootBeanClass=class org.shanoir.ng.datasetacquisition.model.mr.MrDatasetAcquisition, messageTemplate='{javax.validation.constraints.NotNull.message}'}
], please contact an administrator.
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:179)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createAllDatasetAcquisitions(DatasetAcquisitionApiController.java:118)
	at org.shanoir.ng.datasetacquisition.controler.DatasetAcquisitionApiController.createNewDatasetAcquisition(DatasetAcquisitionApiController.java:105)
	... 30 common frames omitted
Caused by: javax.validation.ConstraintViolationException: Validation failed for classes [org.shanoir.ng.datasetacquisition.model.mr.MrDatasetAcquisition] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='**may not be null', propertyPath=acquisitionEquipmentId**, rootBeanClass=class org.shanoir.ng.datasetacquisition.model.mr.MrDatasetAcquisition, messageTemplate='{javax.validation.constraints.NotNull.message}'}

solved by adding acqEquip to ImportJob, sent by ShUp

**Comment by michaelkain** [comment]
2020-08-10 14:28:08.335  WARN 1 --- [http-nio-9902-exec-9] o.s.n.s.c.GlobalExceptionHandler         : Acces denied in the rest service. 

org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.shanoir.ng.subject.controler.SubjectApiController$$EnhancerBySpringCGLIB$$31f73e94.saveNewSubject(<generated>)

**Comment by michaelkain** [comment]
Access is denied above: I had to set Rel-Subject-Study with the saveNewSubject() to solve it, now done in one call from ShUp

**Comment by michaelkain** [comment]
New subject created, with new exam created, now working, but error in task list:

![Bildschirmfoto 2020-08-10 um 15 05 00](https://user-images.githubusercontent.com/4560288/89785567-e8d30e80-db1a-11ea-8a5d-8c3d2d940ae9.png)

**Comment by michaelkain** [comment]
null(84): Successfully created datasets for subject null in examination 12944

**Comment by michaelkain** [comment]
Temporary solution (only working for single-subject import): added subjectName and studyName to ImportJob in ShUp to solve the above display problem

**Comment by michaelkain** [comment]
New bug: with existing subject, but import into another study

Caused by: java.lang.IllegalStateException: Already had POJO for id (java.lang.Long) [[ObjectId: key=153, type=com.fasterxml.jackson.databind.deser.impl.PropertyBasedObjectIdGenerator, scope=org.shanoir.ng.study.model.Study]]
	at com.fasterxml.jackson.annotation.SimpleObjectIdResolver.bindItem(SimpleObjectIdResolver.java:24)
	at com.fasterxml.jackson.databind.deser.impl.ReadableObjectId.bindItem(ReadableObjectId.java:57)
	at com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty.deserializeSetAndReturn(ObjectIdValueProperty.java:90)
	at com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty.deserializeAndSet(ObjectIdValueProperty.java:72)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:357)

**Comment by michaelkain** [comment]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Already had POJO for id (java.lang.Long) [[ObjectId: key=153, type=com.fasterxml.jackson.databind.deser.impl.PropertyBasedObjectIdGenerator, scope=org.shanoir.ng.study.model.Study]] (through reference chain: org.shanoir.ng.subject.model.Subject["subjectStudyList"]->java.util.ArrayList[2]->org.shanoir.ng.subjectstudy.model.SubjectStudy["study"]->org.shanoir.ng.study.model.Study["id"])

**Comment by michaelkain** [comment]
2020-08-10 17:09:27.374  WARN 1 --- [http-nio-9902-exec-4] o.s.n.s.c.GlobalExceptionHandler         : Acces denied in the rest service. 

org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.shanoir.ng.subject.controler.SubjectApiController$$EnhancerBySpringCGLIB$$31f73e94.updateSubject(<generated>)

**Comment by michaelkain** [comment]
I did a lot of testing with qualif, all test cases work now
