### ISSUE TITLE
Qualif: import dicom zip ACTIDEP is failing

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#423]
![Bildschirmfoto 2020-08-04 um 10 16 56](https://user-images.githubusercontent.com/4560288/89270464-aa7db100-d63b-11ea-8511-4de329121672.png)

2020-08-04 10:13:21.388 ERROR 1 --- [http-nio-9903-exec-1] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service. 

java.lang.NullPointerException: null
	at org.shanoir.ng.importer.dicom.ImagesCreatorAndDicomFileAnalyzerService.createImagesAndAnalyzeDicomFiles(ImagesCreatorAndDicomFileAnalyzerService.java:86)
	at org.shanoir.ng.importer.ImporterApiController.uploadDicomZipFile(ImporterApiController.java:238)

**Comment by michaelkain** [comment]
The ACTIDEP.zip file contains a DICOMDIR, but the DICOMDIR is in a folder, and not in the root folder of the zip after unzip.
This caused the issue. In sh-old there is some logic, that searches the DICOMDIR (wherever in the zip), reads it and modifies the paths to the dicom files, that are relative to the DICOMDIR. The fix now stops this behaviour and generates a new DICOMDIR, if there is no DICOMDIR in the root folder. This is somehow a workaround, but as we want to propose in the future the none-DICOMDIR import, the result will be the same.

For ACTIDEP.zip the resulting series are the same:
![Bildschirmfoto 2020-08-05 um 10 18 03](https://user-images.githubusercontent.com/4560288/89392821-51308300-d70a-11ea-8fe4-3dc4f6950ab7.png)
![Bildschirmfoto 2020-08-05 um 10 18 12](https://user-images.githubusercontent.com/4560288/89392824-5261b000-d70a-11ea-9514-8d92afedf873.png)

**Comment by michaelkain** [comment]
Fixed, successfully tested on qualif
