### ISSUE TITLE
Qualif: with ShUp: filterStudyCards exception

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#431]
2020-08-10 15:00:08.419 ERROR 1 --- [http-nio-9904-exec-9] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service. 

java.lang.NullPointerException: null
	at org.shanoir.ng.dataset.security.DatasetSecurityService.filterStudyCardList(DatasetSecurityService.java:480)
	at sun.reflect.GeneratedMethodAccessor208.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:113)
	at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:129)
	at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:170)
	at org.springframework.expression.spel.ast.OpAnd.getBooleanValue(OpAnd.java:56)
	at org.springframework.expression.spel.ast.OpAnd.getValueInternal(OpAnd.java:51)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:170)
	at org.springframework.expression.spel.ast.OpOr.getBooleanValue(OpOr.java:55)
	at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:50)
	at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:36)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:299)
	at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:26)
	at org.springframework.security.access.expression.method.ExpressionBasedPostInvocationAdvice.after(ExpressionBasedPostInvocationAdvice.java:73)
	at org.springframework.security.access.prepost.PostInvocationAdviceProvider.decide(PostInvocationAdviceProvider.java:56)
	at org.springframework.security.access.intercept.AfterInvocationProviderManager.decide(AfterInvocationProviderManager.java:82)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.afterInvocation(AbstractSecurityInterceptor.java:317)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:74)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.shanoir.ng.studycard.controler.StudyCardApiController$$EnhancerBySpringCGLIB$$7c702edc.searchStudyCards(<generated>)

**Comment by Nunien** [comment]
I think #446 will fix it.
