### ISSUE TITLE
ShanoirUploader: downloadDataset.sh not working (probably same for .bat)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#520]
Hi Arthur,

before sharing ShanoirUploader, with ShanoirTK included, with Alban I tested the call from the command line:
./downloadDataset.sh -host shanoir-ng-nginx -port 443 -user xxx -password "xxx" -datasetId xxx

Please see my test setup:
![Bildschirmfoto 2020-09-23 um 09 26 49](https://user-images.githubusercontent.com/4560288/93980707-48117900-fd7f-11ea-935b-bf0b7605781f.png)

I received the following error with multiple host changes:

/Users/mkain/.su_v7.0.0/profile.sh-ng-localhost/profile.properties (No such file or directory)
null
Downloading dataset 32531...
09:20:46,536 ERROR [HttpService] **Target host is null**
java.lang.IllegalStateException: Target host is null
	at org.apache.http.util.Asserts.notNull(Asserts.java:46)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.shanoir.uploader.service.rest.HttpService.get(HttpService.java:83)
	at org.shanoir.uploader.service.rest.ShanoirUploaderServiceClientNG.downloadDatasetById(ShanoirUploaderServiceClientNG.java:298)
	at org.shanoir.downloader.ShanoirDownloader.downloadDataset(ShanoirDownloader.java:352)
	at org.shanoir.downloader.ShanoirDownloader.download(ShanoirDownloader.java:454)
	at org.shanoir.downloader.ShanoirDownloader.main(ShanoirDownloader.java:176)
java.lang.**NullPointerException**
	at org.shanoir.uploader.service.rest.ShanoirUploaderServiceClientNG.downloadDatasetById(ShanoirUploaderServiceClientNG.java:300)
	at org.shanoir.downloader.ShanoirDownloader.downloadDataset(ShanoirDownloader.java:352)
	at org.shanoir.downloader.ShanoirDownloader.download(ShanoirDownloader.java:454)
	at org.shanoir.downloader.ShanoirDownloader.main(ShanoirDownloader.java:176)
09:20:46,538 ERROR [ShanoirCLI] Download failed: null

Could you please fix this?

**Comment by arthursw** [comment]
Yes, I'll have a look!

**Comment by michaelkain** [comment]
Great, thx!

**Comment by arthursw** [comment]
I think "/Users/mkain/.su_v7.0.0/profile.sh-ng-localhost/profile.properties " is the problem, you need to have the the proper config files, I'll add more details in a minute.

**Comment by arthursw** [comment]
so, here is my `/home/amasson/.su_v7.0.0/`
```
/home/amasson/.su_v7.0.0/
├── basic.properties
└── profile.sh-ng-localhost
    ├── keycloak.json
    └── profile.properties

```

**Comment by arthursw** [comment]
`basic.properties` is just:
```
random.seed=0(base)
```

and `/home/amasson/.su_v7.0.0/profile.sh-ng-localhost/` is just a copy of `shanoir-uploard/src/main/resources/profile.dev-NG`

**Comment by michaelkain** [comment]
these files are present for ShUp, when he starts, but with the command line we have to take the values we get on the command line?

**Comment by michaelkain** [comment]
we can not ask the users to create these files manually when running on downloadDataset.sh from the command line, maybe they never run ShUp with GUI

**Comment by michaelkain** [comment]
we can discuss this together if you like

**Comment by arthursw** [comment]
Ok, the code reading the config files is inherited from ShanoirTK.

How should we handle resources files? 
I'm not sure to know how the tool will be released / published. 
One way would be to embed the properties in `application.yml` so that it is published with the .jar?

Although I feel it's more clean to read the original properties files shared with ShanoirUploader GUI ; having those information duplicated won't be good for maintenance.

So could ship the original properties files in `src/main/resources/` with the .jar?

**Comment by michaelkain** [comment]
could you connect to the daily room, better than writing long texts :-)

**Comment by michaelkain** [comment]
summary: read in memory from .jar content of prop files from profile dev-NG, and use host name from command line to init HttpService, and it should be fine, hopefully, thank you and cheers, Michael

**Comment by arthursw** [comment]
PR created 👍 :)

**Comment by michaelkain** [comment]
Hi Arthur, it does still not work because of: 10:51:11,396 ERROR [ShanoirCLI] Keycloak is unreachable. IO exception
javax.net.ssl.SSLException: hostname in certificate didn't match: <shanoir-qualif.irisa.fr> != <shanoir-2016.irisa.fr> OR <shanoir-2016.irisa.fr>, as I solved this error already in ShUp I will take care of it.

**Comment by michaelkain** [comment]
maybe only on my env

**Comment by michaelkain** [comment]
but I fixed it

**Comment by arthursw** [comment]
I don't understand this error, but it's good that you fixed it!

**Comment by michaelkain** [comment]
it worked, I could download a dataset
