### ISSUE TITLE
[Roles] "User" users has access to almost nothing.

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#576]
Study, examination, subjects, acquisition, etc.. are empty fo SOME simple users.
Update=> User Benjamin lemasson has access to almost nothing.

2020-10-08 17:23:29.112  WARN 1 --- [http-nio-9902-exec-1] o.s.n.s.c.GlobalExceptionHandler         : Acces denied in the rest service.
org.springframework.security.access.AccessDeniedException: Accès refusé
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.shanoir.ng.study.controler.StudyApiController$$EnhancerBySpringCGLIB$$be5a433c.findStudies(<generated>)

beforeInvocation => it's  hasAnyRole('ADMIN', 'EXPERT', 'USER') that returns false.

But he is a user (3) in DB.

=> Julien update the user to set it to expert then to user again, and it worked. We think it forced the update into keycloak.
This means that there is probably other "users" not having access to their data => How to know about them ?

**Comment by jcomedouteau** [comment]
This is linked to "guest" role disappearing. I tested locally a "user" user with only "guest" role on keycloak has access to almost nothing.
It is quite easy to get the list of "guest only" on keycloak database
 select * from USER_ENTITY where id not in (select USER_ID from USER_ROLE_MAPPING where ROLE_ID in (SELECT ID from KEYCLOAK_ROLE where NAME in ('ROLE_USER', 'ROLE_ADMIN', 'ROLE_EXPERT')));

(attention, retirer 'admin' and shanoir_user_management)


We need to make a DB update or update all the users one by one => How do you think we can do this @michaelkain @Nunien  ?

**Comment by jcomedouteau** [comment]
To be checked => MD still had an error yesterday
