### ISSUE TITLE
ShUp: login with KeycloakInstalled.loginDesktop not working

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#615]
For a study inside the hospital when starting ShUp, the user can enter using the browser his credentials and the browser displays a successful login, but afterwards an exception is thrown within ShUp: loginDesktop() method, see stack trace.
Highly probably the firewall inside the hospital is blocking the SocketConnection back from the server to KeycloakInstalled.

2020-10-19 10:35:24 INFO  [org.shanoir.uploader.service.rest.ShanoirUploaderServiceClientNG] [130] ShanoirUploaderServiceNG successfully initialized.
2020-10-19 10:35:48 ERROR [org.shanoir.uploader.action.init.AuthenticationConfigurationState] [66] Connection timed out: connect
**java.net.ConnectException: Connection timed out: connect**
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:522)
	at org.keycloak.adapters.SniSSLSocketFactory.connectSocket(SniSSLSocketFactory.java:109)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:401)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:178)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.keycloak.adapters.ServerRequest.invokeAccessCodeToToken(ServerRequest.java:111)
	at org.keycloak.adapters.installed.KeycloakInstalled.processCode(KeycloakInstalled.java:572)
	at org.keycloak.adapters.installed.KeycloakInstalled.loginDesktop(KeycloakInstalled.java:192)
	at org.shanoir.uploader.action.init.AuthenticationConfigurationState.load(AuthenticationConfigurationState.java:45)

**Comment by michaelkain** [comment]
waiting for test in hospital

**Comment by michaelkain** [comment]
successfully tested in hospital
