### ISSUE TITLE
MS Datasets could not be launched in debug mode inside Eclipse with Spring tools plugin

### ISSUE THREAD

**Issue by yyao1231** [fli-iam/shanoir-ng#718]
MS Import could be launched in debug mode inside Eclipse with Spring tools plugin. That is really helpful for hot code replace for development. However, the same thing could not work in ms Datasets, with the same configuration.
Here is the error:

```
...
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:988)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:718)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:650)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:468)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:143)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	... 83 common frames omitted
Caused by: java.net.UnknownHostException: database
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:188)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 106 common frames omitted

```

**Comment by yyao1231** [comment]
PS, if environment variable errors have been encountered before, don't hesitate to configure them like this:
![image](https://user-images.githubusercontent.com/12045953/102369050-d16dcb80-3fbb-11eb-85c2-daf66ebaf5c7.png)

**Comment by yyao1231** [comment]
See wiki here: https://github.com/fli-iam/shanoir-ng/wiki/Remote-debugging
The question now is: what is the difference between ms datasets and import in the database config part?

**Comment by yyao1231** [comment]
Precision: remote debugging in ms datasets works fine, as before. But the ms datasets could not be launched with spring tools plugin in debug mode, as described on the wiki, to do the hot code replace, as the ms import.

**Comment by michaelkain** [comment]
######################################
# DO NOT COMMIT VALUES MODIFICATIONS #
######################################
server:
  port: 9923
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3307/datasets?useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&characterEncoding=utf-8&useSSL=false
    initialize: true
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, validate)
      ddl-auto: create
    # Show or not log for each sql query
    show-sql: true
  rabbitmq:
    host: localhost
front.server:
  address: https://shanoir-ng-nginx/shanoir-ng/
  url: https://shanoir-ng-nginx
keycloak:
  auth-server-url: https://shanoir-ng-nginx/auth
dcm4chee-arc:
  host: dcm4chee-arc
# Solr
spring.data.solr.host: http://solr:8983/solr/shanoir/
# microservices url
ms.url:
  shanoir-ng-studies: http://studies:9902/
# Data folder configuration
datasets-data: /var/datasets-data #your disk
bids-data-folder: /var/datasets-data/bids-data #your disk
# logging configuration
logging:
  file: /var/log/shanoir-ng-logs/shanoir-ng-datasets.log
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

**Comment by yyao1231** [comment]
Hi @michaelkain 
These configs work fine to connect the ms datasets to the database. Thanks! 
I added the certificat of shanoir-ng-nginx to my keystore also (I edited the wiki by the way)
```
PS C:\windows\system32> cd 'C:\Program Files\Java\jdk1.8.0_211\bin\'
PS C:\Program Files\Java\jdk1.8.0_211\bin> .\keytool.exe -import -alias shanoir-ng-nginx -file C:\Users\yyao\Desktop\shanoir-ng-nginx.crt -keystore ..\jre\lib\security\cacerts
Entrez le mot de passe du fichier de clés :
Propriétaire : CN=shanoir-ng-nginx
Emetteur : CN=shanoir-ng-nginx
Numéro de série : b5beda7d4f1246e5
Valide du : Fri Dec 11 10:37:28 CET 2020 au : Sun Dec 11 10:37:28 CET 2022
Empreintes du certificat :
         MD5 : C1:D4:23:40:DA:7C:23:93:96:7C:46:83:ED:AF:FF:26
         SHA1 : 9D:D1:30:27:60:D6:6E:38:C7:7D:98:9B:29:CC:4C:6E:77:AB:1A:F8
         SHA256 : 74:6C:91:8B:FF:5B:35:A9:9B:56:CC:68:19:EE:72:26:25:FE:D8:35:42:EE:94:D7:85:A9:30:9C:A5:30:4A:BD
Nom de l'algorithme de signature : SHA256withRSA
Algorithme de clé publique du sujet : Clé RSA 2048 bits
Version : 1
Faire confiance à ce certificat ? [non] :  oui
Certificat ajouté au fichier de clés
```
But now I get 404 Not found error with the backend of datasets, using spring boot plugin in Eclipse.
Do you have some ideas? @michaelkain @jcomedouteau 

Thanks!

**Comment by yyao1231** [comment]
Otherwise, the hot code replace and debugging works fine for the ms import, after the certificat config. 
There should be other difference between the ms datasets and import config, to have the same behavior about debugging.

**Comment by yyao1231** [comment]
resolved on pet branch
