### ISSUE TITLE
[Angular10] Preclinical exam detail

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#745]
Go on the preclinical examination list
Open a preclinical exam by clicking on it

=> It does not even change page

Uncaught (in promise): NullInjectorError: R3InjectorError(e)[e -> e -> e]: 
  NullInjectorError: No provider for e!
NullInjectorError: R3InjectorError(e)[e -> e -> e]: 
  NullInjectorError: No provider for e!
    at Ye.get (https://shanoir-qualif.irisa.fr/shanoir-ng/main-es2015.e79283c7d6c88fec0d2b.js:1:54045)
    at ro.get (https://shanoir-qualif.irisa.fr/shanoir-ng/main-es2015.e79283c7d6c88fec0d2b.js:1:99390)
    at ro.get (https://shanoir-qualif.irisa.fr/shanoir-ng/main-es2015.e79283c7d6c88fec0d2b.js:1:99390)
    at ro.get (https://shanoir-qualif.irisa.fr/shanoir-ng/main-es2015.e79283c7d6c88fec0d2b.js:1:99390)
    at Nc.get (https://shanoir-qualif.irisa.fr/shanoir-ng/main-es2015.e79283c7d6c88fec0d2b.js:1:148354)
    at Object.get (https://shanoir-qualif.irisa.fr/shanoir-ng/main-es2015.e79283c7d6c88fec0d2b.js:1:132829)
    at ri (https://shanoir-qualif.irisa.fr/shanoir-ng/main-es2015.e79283c7d6c88fec0d2b.js:1:65942)
    at Po (https://shanoir-qualif.irisa.fr/shanoir-ng/main-es2015.e79283c7d6c88fec0d2b.js:1:105730)
    at Rn.e.ɵfac [as factory] (https://shanoir-qualif.irisa.fr/shanoir-ng/main-es2015.e79283c7d6c88fec0d2b.js:3:12641

When entering specificaly the route preclinical-examination/details/ID => same error

**Comment by arthursw** [comment]
Probably related to #750

**Comment by arthursw** [comment]
Probably fixed with #753
