### ISSUE TITLE
Blocking bug on Qualif : 500 when deploying a subject in study tree

### ISSUE THREAD

**Issue by Nunien** [fli-iam/shanoir-ng#774]
On /study/details/2 as admin, trying to deploy 01004 (PATIENT) 

500 error from 
GET | https://shanoir-qualif.irisa.fr/shanoir-ng/datasets/examinations/subject/51/study/2
no details, I can't see the logs for now

could be because of a script about dataOf that couldn't be executed for now

**Comment by yyao1231** [comment]
```
2021-01-15 15:18:46.180 ERROR 1 --- [nio-9904-exec-9] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service.

java.lang.NullPointerException: null
        at org.shanoir.ng.examination.controler.ExaminationApiController$1.compare(ExaminationApiController.java:315)
        at org.shanoir.ng.examination.controler.ExaminationApiController$1.compare(ExaminationApiController.java:312)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.util.TimSort.sort(TimSort.java:220)
        at java.util.Arrays.sort(Arrays.java:1438)
        at java.util.List.sort(List.java:478)
        at org.shanoir.ng.examination.controler.ExaminationApiController.orderDatasetAcquisitions(ExaminationApiController.java:312)
        at org.shanoir.ng.examination.controler.ExaminationApiController.findExaminationsBySubjectIdStudyId(ExaminationApiController.java:218)

```

**Comment by yyao1231** [comment]
and by the way, as discussed yesterday, to test the dataOf implementation of Jean-Côme, the subject should be shared between original study and derived study now.

**Comment by jcomedouteau** [comment]
I'm on it! And trying to correct the mess of dataOf too :)
