### ISSUE TITLE
[PROD] Error while downloading dataset

### ISSUE THREAD

**Issue by jcomedouteau** [fli-iam/shanoir-ng#778]
Actidep datasets on prod:

2021-01-19 09:25:51.930  WARN 1 --- [http-nio-9904-exec-5] o.s.n.s.c.GlobalExceptionHandler         : Error in the rest service. 

org.shanoir.ng.shared.exception.RestServiceException: null
	at org.shanoir.ng.dataset.controler.DatasetApiController.downloadDatasetById(DatasetApiController.java:313)
	at org.shanoir.ng.dataset.controler.DatasetApiController$$FastClassBySpringCGLIB$$c20c6b6b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at 
org.springframework.web.client.HttpClientErrorException: 404 DICOM object not found! objectUID:1.3.12.2.1107.5.2.43.166066.30000019101113324298400007375
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498)
	at org.shanoir.ng.download.WADODownloaderService.downloadFileFromPACS(WADODownloaderService.java:176)
	at org.shanoir.ng.download.WADODownloaderService.downloadDicomFilesForURLs(WADODownloaderService.java:123)
	at org.shanoir.ng.dataset.controler.DatasetApiController.massiveDownload(DatasetApiController.java:406)
	at org.shanoir.ng.dataset.controler.DatasetApiController.massiveDownloadByDatasetIds(DatasetApiController.java:359)
	at org.shanoir.ng.dataset.controler.DatasetApiController$$FastClassBySpringCGLIB$$c20c6b6b.invoke(<generated>)

2021-01-19 09:26:22.855 ERROR 1 --- [http-nio-9904-exec-3] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service. 

org.springframework.web.client.HttpClientErrorException: 404 DICOM object not found! objectUID:1.3.12.2.1107.5.2.43.166066.30000019101113324298400007375
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498)
	at org.shanoir.ng.download.WADODownloaderService.downloadFileFromPACS(WADODownloaderService.java:176)
	at org.shanoir.ng.download.WADODownloaderService.downloadDicomFilesForURLs(WADODownloaderService.java:123)
	at org.shanoir.ng.dataset.controler.DatasetApiController.massiveDownload(DatasetApiController.java:406)
	at org.shanoir.ng.dataset.controler.DatasetApiController.massiveDownloadByDatasetIds(DatasetApiController.java:359)
	at org.shanoir.ng.dataset.controler.DatasetApiController$$FastClassBySpringCGLIB$$c20c6b6b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.shanoir.ng.dataset.controler.DatasetApiController$$EnhancerBySpringCGLIB$$9d656ceb.massiveDownloadByDatasetIds(<generated>)

**Comment by jcomedouteau** [comment]
Dataset ID: 324317

**Comment by jcomedouteau** [comment]
Two dataset expressions, both dicoms

First one:

Second one is a file (which does not exists: file:/var/datasets-data/old/subject_8101/examination11914/examination/dcm2nii_2014-08-04/1.3.12.2.1107.5.2.43.166066.30000019101113324298400007375  => not ending with .nii)

Resting state bold AP physioLog

Ce n'est pas un cas isolé, on a des cas dans toutes les études suivantes:

|   2 | USPIO-6                       |
|   6 | Emodes                        |
|   7 | Moelle                        |
|  11 | Transfert                     |
|  19 | transIRMf                     |
|  22 | DEPRESIST                     |
|  27 | ASLf mt                       |
|  28 | asl_tum                       |
|  30 | PNGI                          |
|  32 | ASL SENSE 2                   |
|  34 | iQALY-SEP                     |
|  37 | ASL DEM                       |
|  38 | Dysphasie                     |
|  39 | NCE MRA                       |
|  40 | VPIPRO                        |
|  42 | SURFER                        |
|  43 | AINSI                         |
|  48 | DEPAPATHIE                    |
|  49 | AfaCorVis3D                   |
|  51 | IQALY-SEP+                    |
|  53 | Emodes_Pilote                 |
|  54 | ATLDIF                        |
|  55 | AVCPOSTIM                     |
|  61 | HEPAT_M                       |
|  66 | TMS Depression                |
|  69 | EPI-DISTO                     |
|  70 | SSS-DIMO                      |
|  71 | Methodo ASL                   |
|  76 | PSY MORPHO ASL                |
|  77 | MS-REPAIR                     |
|  80 | AVCPOSTIM MORPHO              |
|  81 | CAPP-CATI                     |
|  82 | MS-SPI                        |
|  84 | **TEST                        |
|  86 | EMISEP_Pilote                 |
|  87 | LONGIDEP                      |
|  94 | EMISEP                        |
| 100 | OxyTC                         |
| 101 | PERINE                        |
| 108 | Tracto-SCP-Pilote             |
| 109 | Tracto-SCP                    |
| 113 | EPMR-MA Pilote OSS            |
| 114 | HED-O-SHIFT Pilote OSS        |
| 115 | EPMR-MA                       |
| 116 | HED-O-SHIFT                   |
| 118 | COGNISEP Pilote OSS           |
| 119 | PEPS EC                       |
| 128 | QUANT_MRI                     |
| 129 | MB-Diffusion                  |
| 130 | COGNISEP Patients             |
| 132 | FastMicroDiff                 |
| 138 | NeurinfoNG                    |
| 142 | DTI_NOI                       |
| 143 | EMISEP REPRO Diffusion Moelle |
| 144 | Mirror                        |
| 145 | Tests_Prisma                  |
| 147 | evalFLAIR                     |
| 148 | NeuroFB_AVC Pilote            |
| 154 | IMAJ Pilote                   |
| 155 | GLIROPA                       |
| 156 | ADDICTO                       |
| 157 | Etude Patient KA              |
| 162 | NeuroFB_AVC                   |
| 164 | IQCA                          |
| 167 | Neurofeedep                   |
| 168 | Oxydopa                       |
| 169 | ASL_TOC                       |
| 171 | CONFONHIP                     |
| 173 | ACTIDEP                       |
| 174 | CONNECTIFE                    |
| 181 | DEPREDICT                     |
| 183 | AMYNET                        |
| 186 | DBS-Comp                      |
| 188 | IMANES                        |
| 192 | MR_HANDS                      |

**Comment by jcomedouteau** [comment]
Je pense que l'import n'a pas du aller au bout à l'époque mais ça pose quand même problème.

A corriger d'ailleurs, quand on télécharge les DICOM, si l'export d'un dataset échoue, tout échoue (ce n'est pas le cas pour les niftis)

**Comment by jcomedouteau** [comment]
@arthursw I feel like these datasets are actually processed datasets.
Have we thought on how to manage these existing datasets ?

**Comment by arthursw** [comment]
Mhh... Processed datasets cannot be DICOMs. 

Only nifti and Analyze format are accepted, and there are converted to nifti format (if necessary) when imported.

**Comment by jcomedouteau** [comment]
First step to correct this problem is to set the nifti available:

UPDATE dataset_expression de 
INNER JOIN dataset_file df 
ON df.dataset_expression_id = de.id
SET de.dataset_expression_format = 2
WHERE de.dataset_expression_format = 6 and df.pacs is false;

Dicom seems to be unavailable, but we have no way to verify it for the moment as we need to access the PACS
