### ISSUE TITLE
[Challenge] ShUp import not working after changes (qualif)

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#829]
Import test, using ShUp, v7.0.1

    Login works and login successful window now has only one line, great!

    Issue: empty studies list!

    2021-02-17 09:37:36.116 ERROR 1 --- [http-nio-9902-exec-1] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service. 

    java.lang.NullPointerException: null

            at org.shanoir.ng.study.security.StudySecurityService.hasRightOnTrustedSubjectForOneStudy(StudySecurityService.java:206)

            at sun.reflect.GeneratedMethodAccessor275.invoke(Unknown Source)

            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

            at java.lang.reflect.Method.invoke(Method.java:498)

            at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:113)

            at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:102)

            at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)

            at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:347)

            at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)

            at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:170)

            at org.springframework.expression.spel.ast.OpOr.getBooleanValue(OpOr.java:55)

            at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:50)

            at org.springframework.expression.spel.ast.OpOr.getValueInternal(OpOr.java:36)

            at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)

            at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:299)

            at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:26)

            at org.springframework.security.access.expression.method.ExpressionBasedPostInvocationAdvice.after(ExpressionBasedPostInvocationAdvice.java:73)

            at org.springframework.security.access.prepost.PostInvocationAdviceProvider.decide(PostInvocationAdviceProvider.java:56)

            at org.springframework.security.access.intercept.AfterInvocationProviderManager.decide(AfterInvocationProviderManager.java:82)

            at org.springframework.security.access.intercept.AbstractSecurityInterceptor.afterInvocation(AbstractSecurityInterceptor.java:317)

            at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:74)

            at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)

            at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)

            at org.shanoir.ng.subject.service.SubjectServiceImpl$$EnhancerBySpringCGLIB$$d4805f0f.findByIdentifier(<generated>)

            at org.shanoir.ng.subject.controler.SubjectApiController.findSubjectByIdentifier(SubjectApiController.java:173)

            at org.shanoir.ng.subject.controler.SubjectApiController$$FastClassBySpringCGLIB$$ba91d803.invoke(<generated>)

**Comment by michaelkain** [comment]
My analysis: could not reproduce it locally
the server sends 204 no_content to ShUp for the list of studies asked, but there are studies in the db,
but there is no other issue in the logs and the db is correct with study_user

**Comment by michaelkain** [comment]
Bug: the list of studies in ShUp remains empty, the above NPE is a later exception, that is related to a subject not existing in db searched with a specific identifier

**Comment by jcomedouteau** [comment]
I have the same problem on prod, this is quite weird, I'm checking this to get my import done :)

**Comment by jcomedouteau** [comment]
I wonder if it's not linked to keycloak 12.0 and shanoir-uploader client configuration (?)

**Comment by jcomedouteau** [comment]
Error I get (that's quite weird, that's when I load studies...)
2021-02-22 14:27:51.561  WARN 1 --- [http-nio-9902-exec-9] o.s.n.s.c.GlobalExceptionHandler         : Acces denied in the rest service. 

org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.expression.method.ExpressionBasedPostInvocationAdvice.after(ExpressionBasedPostInvocationAdvice.java:77)
	at org.springframework.security.access.prepost.PostInvocationAdviceProvider.decide(PostInvocationAdviceProvider.java:56)
	at org.springframework.security.access.intercept.AfterInvocationProviderManager.decide(AfterInvocationProviderManager.java:82)
	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.afterInvocation(AbstractSecurityInterceptor.java:317)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:74)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.shanoir.ng.subject.service.SubjectServiceImpl$$EnhancerBySpringCGLIB$$5f818ef0.findByIdentifier(<generated>)
	at org.shanoir.ng.subject.controler.SubjectApiController.findSubjectByIdentifier(SubjectApiController.java:173)
	at org.shanoir.ng.subject.controler.SubjectApiController$$FastClassBySpringCGLIB$$ba91d803.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.shanoir.ng.subject.controler.SubjectApiController$$EnhancerBySpringCGLIB$$da1be6f4.findSubjectByIdentifier(<generated>)
