### ISSUE TITLE
shanoir-ng-users log: clean up

### ISSUE THREAD

**Issue by michaelkain** [fli-iam/shanoir-ng#991]
Hi Jean-Come,
the log file of shanoir-ng-users (.log) is quite full of exceptions like the below.
Could you please try to clean it up, as they come from the EventsService?
Thank you and with kind regards,
Michael

2021-07-07 12:10:18.474 ERROR 1 --- [pool-7-thread-1] o.s.ng.events.ShanoirEventsService       : Error while keeping connection alive. 

java.lang.IllegalStateException: The request associated with the AsyncContext has already completed processing.
	at org.apache.catalina.core.AsyncContextImpl.check(AsyncContextImpl.java:497)
	at org.apache.catalina.core.AsyncContextImpl.getRequest(AsyncContextImpl.java:209)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:198)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:170)
	at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:164)
	at org.springframework.security.web.servletapi.HttpServlet3RequestFactory$SecurityContextAsyncContext.dispatch(HttpServlet3RequestFactory.java:291)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:123)
	at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:353)
	at org.springframework.web.context.request.async.WebAsyncManager.access$200(WebAsyncManager.java:58)
	at org.springframework.web.context.request.async.WebAsyncManager$7.handleResult(WebAsyncManager.java:416)
	at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:199)
	at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:214)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitterReturnValueHandler$HttpMessageConvertingHandler.completeWithError(ResponseBodyEmitterReturnValueHandler.java:219)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.completeWithError(ResponseBodyEmitter.java:204)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.sendInternal(ResponseBodyEmitter.java:169)
	at org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter.send(ResponseBodyEmitter.java:159)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:125)
	at org.springframework.web.servlet.mvc.method.annotation.SseEmitter.send(SseEmitter.java:106)
	at org.shanoir.ng.events.ShanoirEventsService.lambda$keepConnectionAlive$1(ShanoirEventsService.java:86)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2064)
	at org.shanoir.ng.events.ShanoirEventsService.keepConnectionAlive(ShanoirEventsService.java:84)
	at sun.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jcomedouteau** [comment]
Hi mIchael, 
I saw it some time ago, It is due to the link back -> front to display the tasks live, when the user's session ends.
I'll try to manage it better !
